github: [Laitei40]
patreon:
open_collective:
ko_fi: https://ko-fi.com/laitei
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee: https://ko-fi.com/laitei
thanks_dev:
custom:
